### PR TITLE
Node relations

### PR DESCRIPTION
**Pull request by isabellachen**
Update this plugin so now it is possible to query `venue__NODE` when querying events to get the venue. 

For example, with a query like this:
```
{
  allEventbriteEvents {
    edges {
      node {
        name {
          text
        }
        venue__NODE {
          name
          address {
            address_1
            address_2
            city
          }
        }
      }
    }
  }
}
```

### CODE REVIEW

**Comment by isabellachen** [comment]
Also, I'm unsure of the best way to go about adding or changing node relations since nodes don't get recreated unless the node's internal.contentDigest. A work around is to de-create the nodes and re-create them. You can do this by commenting out the line that uses createNode(), recompile with `gatsby develop` and uncomment the line and recompile but there's probably a better way...

**Comment by sarasate** [comment]
I'll have a look at this next week..

**Comment by isabellachen** [comment]
Ok thanks! Tell me what the problem is when you have time :)

**Pull request merged**
